package com.wisdom.dao.entity;

import java.io.Serializable;
import java.sql.Timestamp;

public class Hospital implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hospital.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hospital.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hospital.SIMPLE_PINYIN
     *
     * @mbggenerated
     */
    private String simplePinyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hospital.AREA_IDS
     *
     * @mbggenerated
     */
    private String areaIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hospital.ADDRESS
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hospital.TYPE
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hospital.LEVEL
     *
     * @mbggenerated
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hospital.IS_DEL
     *
     * @mbggenerated
     */
    private String isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hospital.CREATE_TIME
     *
     * @mbggenerated
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hospital
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hospital.ID
     *
     * @return the value of t_hospital.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hospital.ID
     *
     * @param id the value for t_hospital.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hospital.NAME
     *
     * @return the value of t_hospital.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hospital.NAME
     *
     * @param name the value for t_hospital.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hospital.SIMPLE_PINYIN
     *
     * @return the value of t_hospital.SIMPLE_PINYIN
     *
     * @mbggenerated
     */
    public String getSimplePinyin() {
        return simplePinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hospital.SIMPLE_PINYIN
     *
     * @param simplePinyin the value for t_hospital.SIMPLE_PINYIN
     *
     * @mbggenerated
     */
    public void setSimplePinyin(String simplePinyin) {
        this.simplePinyin = simplePinyin == null ? null : simplePinyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hospital.AREA_IDS
     *
     * @return the value of t_hospital.AREA_IDS
     *
     * @mbggenerated
     */
    public String getAreaIds() {
        return areaIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hospital.AREA_IDS
     *
     * @param areaIds the value for t_hospital.AREA_IDS
     *
     * @mbggenerated
     */
    public void setAreaIds(String areaIds) {
        this.areaIds = areaIds == null ? null : areaIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hospital.ADDRESS
     *
     * @return the value of t_hospital.ADDRESS
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hospital.ADDRESS
     *
     * @param address the value for t_hospital.ADDRESS
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hospital.TYPE
     *
     * @return the value of t_hospital.TYPE
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hospital.TYPE
     *
     * @param type the value for t_hospital.TYPE
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hospital.LEVEL
     *
     * @return the value of t_hospital.LEVEL
     *
     * @mbggenerated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hospital.LEVEL
     *
     * @param level the value for t_hospital.LEVEL
     *
     * @mbggenerated
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hospital.IS_DEL
     *
     * @return the value of t_hospital.IS_DEL
     *
     * @mbggenerated
     */
    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hospital.IS_DEL
     *
     * @param isDel the value for t_hospital.IS_DEL
     *
     * @mbggenerated
     */
    public void setIsDel(String isDel) {
        this.isDel = isDel == null ? null : isDel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hospital.CREATE_TIME
     *
     * @return the value of t_hospital.CREATE_TIME
     *
     * @mbggenerated
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hospital.CREATE_TIME
     *
     * @param createTime the value for t_hospital.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }
}