package com.wisdom.dao.entity;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

public class NurseExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_nurse
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_nurse
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_nurse
     *
     * @mbggenerated
     */
    protected String suffix = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_nurse
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_nurse
     *
     * @mbggenerated
     */
    protected int limitClauseStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_nurse
     *
     * @mbggenerated
     */
    protected int limitClauseCount = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_nurse
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_nurse
     *
     * @mbggenerated
     */
    public NurseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_nurse
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_nurse
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_nurse
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_nurse
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_nurse
     *
     * @mbggenerated
     */
    public void setSuffix(String suffix) {
        this.suffix = suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_nurse
     *
     * @mbggenerated
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_nurse
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_nurse
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_nurse
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_nurse
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_nurse
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_nurse
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_nurse
     *
     * @mbggenerated
     */
    public void setLimitClauseStart(int limitClauseStart) {
        this.limitClauseStart=limitClauseStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_nurse
     *
     * @mbggenerated
     */
    public int getLimitClauseStart() {
        return limitClauseStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_nurse
     *
     * @mbggenerated
     */
    public void setLimitClauseCount(int limitClauseCount) {
        this.limitClauseCount=limitClauseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_nurse
     *
     * @mbggenerated
     */
    public int getLimitClauseCount() {
        return limitClauseCount;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_nurse
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAccountIdIsNull() {
            addCriterion("ACCOUNT_ID is null");
            return (Criteria) this;
        }

        public Criteria andAccountIdIsNotNull() {
            addCriterion("ACCOUNT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAccountIdEqualTo(Integer value) {
            addCriterion("ACCOUNT_ID =", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotEqualTo(Integer value) {
            addCriterion("ACCOUNT_ID <>", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdGreaterThan(Integer value) {
            addCriterion("ACCOUNT_ID >", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ACCOUNT_ID >=", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdLessThan(Integer value) {
            addCriterion("ACCOUNT_ID <", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdLessThanOrEqualTo(Integer value) {
            addCriterion("ACCOUNT_ID <=", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdIn(List<Integer> values) {
            addCriterion("ACCOUNT_ID in", values, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotIn(List<Integer> values) {
            addCriterion("ACCOUNT_ID not in", values, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdBetween(Integer value1, Integer value2) {
            addCriterion("ACCOUNT_ID between", value1, value2, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ACCOUNT_ID not between", value1, value2, "accountId");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("SEX is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("SEX is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("SEX =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("SEX <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("SEX >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("SEX >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("SEX <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("SEX <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("SEX like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("SEX not like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<String> values) {
            addCriterion("SEX in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<String> values) {
            addCriterion("SEX not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("SEX between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("SEX not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andAgeIsNull() {
            addCriterion("AGE is null");
            return (Criteria) this;
        }

        public Criteria andAgeIsNotNull() {
            addCriterion("AGE is not null");
            return (Criteria) this;
        }

        public Criteria andAgeEqualTo(String value) {
            addCriterion("AGE =", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotEqualTo(String value) {
            addCriterion("AGE <>", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThan(String value) {
            addCriterion("AGE >", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThanOrEqualTo(String value) {
            addCriterion("AGE >=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThan(String value) {
            addCriterion("AGE <", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThanOrEqualTo(String value) {
            addCriterion("AGE <=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLike(String value) {
            addCriterion("AGE like", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotLike(String value) {
            addCriterion("AGE not like", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeIn(List<String> values) {
            addCriterion("AGE in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotIn(List<String> values) {
            addCriterion("AGE not in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeBetween(String value1, String value2) {
            addCriterion("AGE between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotBetween(String value1, String value2) {
            addCriterion("AGE not between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andSimplePinyinIsNull() {
            addCriterion("SIMPLE_PINYIN is null");
            return (Criteria) this;
        }

        public Criteria andSimplePinyinIsNotNull() {
            addCriterion("SIMPLE_PINYIN is not null");
            return (Criteria) this;
        }

        public Criteria andSimplePinyinEqualTo(String value) {
            addCriterion("SIMPLE_PINYIN =", value, "simplePinyin");
            return (Criteria) this;
        }

        public Criteria andSimplePinyinNotEqualTo(String value) {
            addCriterion("SIMPLE_PINYIN <>", value, "simplePinyin");
            return (Criteria) this;
        }

        public Criteria andSimplePinyinGreaterThan(String value) {
            addCriterion("SIMPLE_PINYIN >", value, "simplePinyin");
            return (Criteria) this;
        }

        public Criteria andSimplePinyinGreaterThanOrEqualTo(String value) {
            addCriterion("SIMPLE_PINYIN >=", value, "simplePinyin");
            return (Criteria) this;
        }

        public Criteria andSimplePinyinLessThan(String value) {
            addCriterion("SIMPLE_PINYIN <", value, "simplePinyin");
            return (Criteria) this;
        }

        public Criteria andSimplePinyinLessThanOrEqualTo(String value) {
            addCriterion("SIMPLE_PINYIN <=", value, "simplePinyin");
            return (Criteria) this;
        }

        public Criteria andSimplePinyinLike(String value) {
            addCriterion("SIMPLE_PINYIN like", value, "simplePinyin");
            return (Criteria) this;
        }

        public Criteria andSimplePinyinNotLike(String value) {
            addCriterion("SIMPLE_PINYIN not like", value, "simplePinyin");
            return (Criteria) this;
        }

        public Criteria andSimplePinyinIn(List<String> values) {
            addCriterion("SIMPLE_PINYIN in", values, "simplePinyin");
            return (Criteria) this;
        }

        public Criteria andSimplePinyinNotIn(List<String> values) {
            addCriterion("SIMPLE_PINYIN not in", values, "simplePinyin");
            return (Criteria) this;
        }

        public Criteria andSimplePinyinBetween(String value1, String value2) {
            addCriterion("SIMPLE_PINYIN between", value1, value2, "simplePinyin");
            return (Criteria) this;
        }

        public Criteria andSimplePinyinNotBetween(String value1, String value2) {
            addCriterion("SIMPLE_PINYIN not between", value1, value2, "simplePinyin");
            return (Criteria) this;
        }

        public Criteria andIdCodeIsNull() {
            addCriterion("ID_CODE is null");
            return (Criteria) this;
        }

        public Criteria andIdCodeIsNotNull() {
            addCriterion("ID_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andIdCodeEqualTo(String value) {
            addCriterion("ID_CODE =", value, "idCode");
            return (Criteria) this;
        }

        public Criteria andIdCodeNotEqualTo(String value) {
            addCriterion("ID_CODE <>", value, "idCode");
            return (Criteria) this;
        }

        public Criteria andIdCodeGreaterThan(String value) {
            addCriterion("ID_CODE >", value, "idCode");
            return (Criteria) this;
        }

        public Criteria andIdCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ID_CODE >=", value, "idCode");
            return (Criteria) this;
        }

        public Criteria andIdCodeLessThan(String value) {
            addCriterion("ID_CODE <", value, "idCode");
            return (Criteria) this;
        }

        public Criteria andIdCodeLessThanOrEqualTo(String value) {
            addCriterion("ID_CODE <=", value, "idCode");
            return (Criteria) this;
        }

        public Criteria andIdCodeLike(String value) {
            addCriterion("ID_CODE like", value, "idCode");
            return (Criteria) this;
        }

        public Criteria andIdCodeNotLike(String value) {
            addCriterion("ID_CODE not like", value, "idCode");
            return (Criteria) this;
        }

        public Criteria andIdCodeIn(List<String> values) {
            addCriterion("ID_CODE in", values, "idCode");
            return (Criteria) this;
        }

        public Criteria andIdCodeNotIn(List<String> values) {
            addCriterion("ID_CODE not in", values, "idCode");
            return (Criteria) this;
        }

        public Criteria andIdCodeBetween(String value1, String value2) {
            addCriterion("ID_CODE between", value1, value2, "idCode");
            return (Criteria) this;
        }

        public Criteria andIdCodeNotBetween(String value1, String value2) {
            addCriterion("ID_CODE not between", value1, value2, "idCode");
            return (Criteria) this;
        }

        public Criteria andIdPathIsNull() {
            addCriterion("ID_PATH is null");
            return (Criteria) this;
        }

        public Criteria andIdPathIsNotNull() {
            addCriterion("ID_PATH is not null");
            return (Criteria) this;
        }

        public Criteria andIdPathEqualTo(String value) {
            addCriterion("ID_PATH =", value, "idPath");
            return (Criteria) this;
        }

        public Criteria andIdPathNotEqualTo(String value) {
            addCriterion("ID_PATH <>", value, "idPath");
            return (Criteria) this;
        }

        public Criteria andIdPathGreaterThan(String value) {
            addCriterion("ID_PATH >", value, "idPath");
            return (Criteria) this;
        }

        public Criteria andIdPathGreaterThanOrEqualTo(String value) {
            addCriterion("ID_PATH >=", value, "idPath");
            return (Criteria) this;
        }

        public Criteria andIdPathLessThan(String value) {
            addCriterion("ID_PATH <", value, "idPath");
            return (Criteria) this;
        }

        public Criteria andIdPathLessThanOrEqualTo(String value) {
            addCriterion("ID_PATH <=", value, "idPath");
            return (Criteria) this;
        }

        public Criteria andIdPathLike(String value) {
            addCriterion("ID_PATH like", value, "idPath");
            return (Criteria) this;
        }

        public Criteria andIdPathNotLike(String value) {
            addCriterion("ID_PATH not like", value, "idPath");
            return (Criteria) this;
        }

        public Criteria andIdPathIn(List<String> values) {
            addCriterion("ID_PATH in", values, "idPath");
            return (Criteria) this;
        }

        public Criteria andIdPathNotIn(List<String> values) {
            addCriterion("ID_PATH not in", values, "idPath");
            return (Criteria) this;
        }

        public Criteria andIdPathBetween(String value1, String value2) {
            addCriterion("ID_PATH between", value1, value2, "idPath");
            return (Criteria) this;
        }

        public Criteria andIdPathNotBetween(String value1, String value2) {
            addCriterion("ID_PATH not between", value1, value2, "idPath");
            return (Criteria) this;
        }

        public Criteria andRelationIsNull() {
            addCriterion("RELATION is null");
            return (Criteria) this;
        }

        public Criteria andRelationIsNotNull() {
            addCriterion("RELATION is not null");
            return (Criteria) this;
        }

        public Criteria andRelationEqualTo(String value) {
            addCriterion("RELATION =", value, "relation");
            return (Criteria) this;
        }

        public Criteria andRelationNotEqualTo(String value) {
            addCriterion("RELATION <>", value, "relation");
            return (Criteria) this;
        }

        public Criteria andRelationGreaterThan(String value) {
            addCriterion("RELATION >", value, "relation");
            return (Criteria) this;
        }

        public Criteria andRelationGreaterThanOrEqualTo(String value) {
            addCriterion("RELATION >=", value, "relation");
            return (Criteria) this;
        }

        public Criteria andRelationLessThan(String value) {
            addCriterion("RELATION <", value, "relation");
            return (Criteria) this;
        }

        public Criteria andRelationLessThanOrEqualTo(String value) {
            addCriterion("RELATION <=", value, "relation");
            return (Criteria) this;
        }

        public Criteria andRelationLike(String value) {
            addCriterion("RELATION like", value, "relation");
            return (Criteria) this;
        }

        public Criteria andRelationNotLike(String value) {
            addCriterion("RELATION not like", value, "relation");
            return (Criteria) this;
        }

        public Criteria andRelationIn(List<String> values) {
            addCriterion("RELATION in", values, "relation");
            return (Criteria) this;
        }

        public Criteria andRelationNotIn(List<String> values) {
            addCriterion("RELATION not in", values, "relation");
            return (Criteria) this;
        }

        public Criteria andRelationBetween(String value1, String value2) {
            addCriterion("RELATION between", value1, value2, "relation");
            return (Criteria) this;
        }

        public Criteria andRelationNotBetween(String value1, String value2) {
            addCriterion("RELATION not between", value1, value2, "relation");
            return (Criteria) this;
        }

        public Criteria andWorkYearsIsNull() {
            addCriterion("WORK_YEARS is null");
            return (Criteria) this;
        }

        public Criteria andWorkYearsIsNotNull() {
            addCriterion("WORK_YEARS is not null");
            return (Criteria) this;
        }

        public Criteria andWorkYearsEqualTo(String value) {
            addCriterion("WORK_YEARS =", value, "workYears");
            return (Criteria) this;
        }

        public Criteria andWorkYearsNotEqualTo(String value) {
            addCriterion("WORK_YEARS <>", value, "workYears");
            return (Criteria) this;
        }

        public Criteria andWorkYearsGreaterThan(String value) {
            addCriterion("WORK_YEARS >", value, "workYears");
            return (Criteria) this;
        }

        public Criteria andWorkYearsGreaterThanOrEqualTo(String value) {
            addCriterion("WORK_YEARS >=", value, "workYears");
            return (Criteria) this;
        }

        public Criteria andWorkYearsLessThan(String value) {
            addCriterion("WORK_YEARS <", value, "workYears");
            return (Criteria) this;
        }

        public Criteria andWorkYearsLessThanOrEqualTo(String value) {
            addCriterion("WORK_YEARS <=", value, "workYears");
            return (Criteria) this;
        }

        public Criteria andWorkYearsLike(String value) {
            addCriterion("WORK_YEARS like", value, "workYears");
            return (Criteria) this;
        }

        public Criteria andWorkYearsNotLike(String value) {
            addCriterion("WORK_YEARS not like", value, "workYears");
            return (Criteria) this;
        }

        public Criteria andWorkYearsIn(List<String> values) {
            addCriterion("WORK_YEARS in", values, "workYears");
            return (Criteria) this;
        }

        public Criteria andWorkYearsNotIn(List<String> values) {
            addCriterion("WORK_YEARS not in", values, "workYears");
            return (Criteria) this;
        }

        public Criteria andWorkYearsBetween(String value1, String value2) {
            addCriterion("WORK_YEARS between", value1, value2, "workYears");
            return (Criteria) this;
        }

        public Criteria andWorkYearsNotBetween(String value1, String value2) {
            addCriterion("WORK_YEARS not between", value1, value2, "workYears");
            return (Criteria) this;
        }

        public Criteria andWorkHospitalIsNull() {
            addCriterion("WORK_HOSPITAL is null");
            return (Criteria) this;
        }

        public Criteria andWorkHospitalIsNotNull() {
            addCriterion("WORK_HOSPITAL is not null");
            return (Criteria) this;
        }

        public Criteria andWorkHospitalEqualTo(Integer value) {
            addCriterion("WORK_HOSPITAL =", value, "workHospital");
            return (Criteria) this;
        }

        public Criteria andWorkHospitalNotEqualTo(Integer value) {
            addCriterion("WORK_HOSPITAL <>", value, "workHospital");
            return (Criteria) this;
        }

        public Criteria andWorkHospitalGreaterThan(Integer value) {
            addCriterion("WORK_HOSPITAL >", value, "workHospital");
            return (Criteria) this;
        }

        public Criteria andWorkHospitalGreaterThanOrEqualTo(Integer value) {
            addCriterion("WORK_HOSPITAL >=", value, "workHospital");
            return (Criteria) this;
        }

        public Criteria andWorkHospitalLessThan(Integer value) {
            addCriterion("WORK_HOSPITAL <", value, "workHospital");
            return (Criteria) this;
        }

        public Criteria andWorkHospitalLessThanOrEqualTo(Integer value) {
            addCriterion("WORK_HOSPITAL <=", value, "workHospital");
            return (Criteria) this;
        }

        public Criteria andWorkHospitalIn(List<Integer> values) {
            addCriterion("WORK_HOSPITAL in", values, "workHospital");
            return (Criteria) this;
        }

        public Criteria andWorkHospitalNotIn(List<Integer> values) {
            addCriterion("WORK_HOSPITAL not in", values, "workHospital");
            return (Criteria) this;
        }

        public Criteria andWorkHospitalBetween(Integer value1, Integer value2) {
            addCriterion("WORK_HOSPITAL between", value1, value2, "workHospital");
            return (Criteria) this;
        }

        public Criteria andWorkHospitalNotBetween(Integer value1, Integer value2) {
            addCriterion("WORK_HOSPITAL not between", value1, value2, "workHospital");
            return (Criteria) this;
        }

        public Criteria andWorkDepartmentIsNull() {
            addCriterion("WORK_DEPARTMENT is null");
            return (Criteria) this;
        }

        public Criteria andWorkDepartmentIsNotNull() {
            addCriterion("WORK_DEPARTMENT is not null");
            return (Criteria) this;
        }

        public Criteria andWorkDepartmentEqualTo(Integer value) {
            addCriterion("WORK_DEPARTMENT =", value, "workDepartment");
            return (Criteria) this;
        }

        public Criteria andWorkDepartmentNotEqualTo(Integer value) {
            addCriterion("WORK_DEPARTMENT <>", value, "workDepartment");
            return (Criteria) this;
        }

        public Criteria andWorkDepartmentGreaterThan(Integer value) {
            addCriterion("WORK_DEPARTMENT >", value, "workDepartment");
            return (Criteria) this;
        }

        public Criteria andWorkDepartmentGreaterThanOrEqualTo(Integer value) {
            addCriterion("WORK_DEPARTMENT >=", value, "workDepartment");
            return (Criteria) this;
        }

        public Criteria andWorkDepartmentLessThan(Integer value) {
            addCriterion("WORK_DEPARTMENT <", value, "workDepartment");
            return (Criteria) this;
        }

        public Criteria andWorkDepartmentLessThanOrEqualTo(Integer value) {
            addCriterion("WORK_DEPARTMENT <=", value, "workDepartment");
            return (Criteria) this;
        }

        public Criteria andWorkDepartmentIn(List<Integer> values) {
            addCriterion("WORK_DEPARTMENT in", values, "workDepartment");
            return (Criteria) this;
        }

        public Criteria andWorkDepartmentNotIn(List<Integer> values) {
            addCriterion("WORK_DEPARTMENT not in", values, "workDepartment");
            return (Criteria) this;
        }

        public Criteria andWorkDepartmentBetween(Integer value1, Integer value2) {
            addCriterion("WORK_DEPARTMENT between", value1, value2, "workDepartment");
            return (Criteria) this;
        }

        public Criteria andWorkDepartmentNotBetween(Integer value1, Integer value2) {
            addCriterion("WORK_DEPARTMENT not between", value1, value2, "workDepartment");
            return (Criteria) this;
        }

        public Criteria andGoodRangeIsNull() {
            addCriterion("GOOD_RANGE is null");
            return (Criteria) this;
        }

        public Criteria andGoodRangeIsNotNull() {
            addCriterion("GOOD_RANGE is not null");
            return (Criteria) this;
        }

        public Criteria andGoodRangeEqualTo(String value) {
            addCriterion("GOOD_RANGE =", value, "goodRange");
            return (Criteria) this;
        }

        public Criteria andGoodRangeNotEqualTo(String value) {
            addCriterion("GOOD_RANGE <>", value, "goodRange");
            return (Criteria) this;
        }

        public Criteria andGoodRangeGreaterThan(String value) {
            addCriterion("GOOD_RANGE >", value, "goodRange");
            return (Criteria) this;
        }

        public Criteria andGoodRangeGreaterThanOrEqualTo(String value) {
            addCriterion("GOOD_RANGE >=", value, "goodRange");
            return (Criteria) this;
        }

        public Criteria andGoodRangeLessThan(String value) {
            addCriterion("GOOD_RANGE <", value, "goodRange");
            return (Criteria) this;
        }

        public Criteria andGoodRangeLessThanOrEqualTo(String value) {
            addCriterion("GOOD_RANGE <=", value, "goodRange");
            return (Criteria) this;
        }

        public Criteria andGoodRangeLike(String value) {
            addCriterion("GOOD_RANGE like", value, "goodRange");
            return (Criteria) this;
        }

        public Criteria andGoodRangeNotLike(String value) {
            addCriterion("GOOD_RANGE not like", value, "goodRange");
            return (Criteria) this;
        }

        public Criteria andGoodRangeIn(List<String> values) {
            addCriterion("GOOD_RANGE in", values, "goodRange");
            return (Criteria) this;
        }

        public Criteria andGoodRangeNotIn(List<String> values) {
            addCriterion("GOOD_RANGE not in", values, "goodRange");
            return (Criteria) this;
        }

        public Criteria andGoodRangeBetween(String value1, String value2) {
            addCriterion("GOOD_RANGE between", value1, value2, "goodRange");
            return (Criteria) this;
        }

        public Criteria andGoodRangeNotBetween(String value1, String value2) {
            addCriterion("GOOD_RANGE not between", value1, value2, "goodRange");
            return (Criteria) this;
        }

        public Criteria andServiceRangeIsNull() {
            addCriterion("SERVICE_RANGE is null");
            return (Criteria) this;
        }

        public Criteria andServiceRangeIsNotNull() {
            addCriterion("SERVICE_RANGE is not null");
            return (Criteria) this;
        }

        public Criteria andServiceRangeEqualTo(String value) {
            addCriterion("SERVICE_RANGE =", value, "serviceRange");
            return (Criteria) this;
        }

        public Criteria andServiceRangeNotEqualTo(String value) {
            addCriterion("SERVICE_RANGE <>", value, "serviceRange");
            return (Criteria) this;
        }

        public Criteria andServiceRangeGreaterThan(String value) {
            addCriterion("SERVICE_RANGE >", value, "serviceRange");
            return (Criteria) this;
        }

        public Criteria andServiceRangeGreaterThanOrEqualTo(String value) {
            addCriterion("SERVICE_RANGE >=", value, "serviceRange");
            return (Criteria) this;
        }

        public Criteria andServiceRangeLessThan(String value) {
            addCriterion("SERVICE_RANGE <", value, "serviceRange");
            return (Criteria) this;
        }

        public Criteria andServiceRangeLessThanOrEqualTo(String value) {
            addCriterion("SERVICE_RANGE <=", value, "serviceRange");
            return (Criteria) this;
        }

        public Criteria andServiceRangeLike(String value) {
            addCriterion("SERVICE_RANGE like", value, "serviceRange");
            return (Criteria) this;
        }

        public Criteria andServiceRangeNotLike(String value) {
            addCriterion("SERVICE_RANGE not like", value, "serviceRange");
            return (Criteria) this;
        }

        public Criteria andServiceRangeIn(List<String> values) {
            addCriterion("SERVICE_RANGE in", values, "serviceRange");
            return (Criteria) this;
        }

        public Criteria andServiceRangeNotIn(List<String> values) {
            addCriterion("SERVICE_RANGE not in", values, "serviceRange");
            return (Criteria) this;
        }

        public Criteria andServiceRangeBetween(String value1, String value2) {
            addCriterion("SERVICE_RANGE between", value1, value2, "serviceRange");
            return (Criteria) this;
        }

        public Criteria andServiceRangeNotBetween(String value1, String value2) {
            addCriterion("SERVICE_RANGE not between", value1, value2, "serviceRange");
            return (Criteria) this;
        }

        public Criteria andLicenseIsNull() {
            addCriterion("LICENSE is null");
            return (Criteria) this;
        }

        public Criteria andLicenseIsNotNull() {
            addCriterion("LICENSE is not null");
            return (Criteria) this;
        }

        public Criteria andLicenseEqualTo(String value) {
            addCriterion("LICENSE =", value, "license");
            return (Criteria) this;
        }

        public Criteria andLicenseNotEqualTo(String value) {
            addCriterion("LICENSE <>", value, "license");
            return (Criteria) this;
        }

        public Criteria andLicenseGreaterThan(String value) {
            addCriterion("LICENSE >", value, "license");
            return (Criteria) this;
        }

        public Criteria andLicenseGreaterThanOrEqualTo(String value) {
            addCriterion("LICENSE >=", value, "license");
            return (Criteria) this;
        }

        public Criteria andLicenseLessThan(String value) {
            addCriterion("LICENSE <", value, "license");
            return (Criteria) this;
        }

        public Criteria andLicenseLessThanOrEqualTo(String value) {
            addCriterion("LICENSE <=", value, "license");
            return (Criteria) this;
        }

        public Criteria andLicenseLike(String value) {
            addCriterion("LICENSE like", value, "license");
            return (Criteria) this;
        }

        public Criteria andLicenseNotLike(String value) {
            addCriterion("LICENSE not like", value, "license");
            return (Criteria) this;
        }

        public Criteria andLicenseIn(List<String> values) {
            addCriterion("LICENSE in", values, "license");
            return (Criteria) this;
        }

        public Criteria andLicenseNotIn(List<String> values) {
            addCriterion("LICENSE not in", values, "license");
            return (Criteria) this;
        }

        public Criteria andLicenseBetween(String value1, String value2) {
            addCriterion("LICENSE between", value1, value2, "license");
            return (Criteria) this;
        }

        public Criteria andLicenseNotBetween(String value1, String value2) {
            addCriterion("LICENSE not between", value1, value2, "license");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNull() {
            addCriterion("IS_DEL is null");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNotNull() {
            addCriterion("IS_DEL is not null");
            return (Criteria) this;
        }

        public Criteria andIsDelEqualTo(String value) {
            addCriterion("IS_DEL =", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotEqualTo(String value) {
            addCriterion("IS_DEL <>", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThan(String value) {
            addCriterion("IS_DEL >", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThanOrEqualTo(String value) {
            addCriterion("IS_DEL >=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThan(String value) {
            addCriterion("IS_DEL <", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThanOrEqualTo(String value) {
            addCriterion("IS_DEL <=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLike(String value) {
            addCriterion("IS_DEL like", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotLike(String value) {
            addCriterion("IS_DEL not like", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelIn(List<String> values) {
            addCriterion("IS_DEL in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotIn(List<String> values) {
            addCriterion("IS_DEL not in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelBetween(String value1, String value2) {
            addCriterion("IS_DEL between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotBetween(String value1, String value2) {
            addCriterion("IS_DEL not between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Timestamp value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Timestamp value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Timestamp value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Timestamp value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Timestamp value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Timestamp value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Timestamp> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Timestamp> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Timestamp value1, Timestamp value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Timestamp value1, Timestamp value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_nurse
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_nurse
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}