package com.wisdom.dao.entity;

import java.io.Serializable;
import java.sql.Timestamp;

public class OrderInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.ORDER_CODE
     *
     * @mbggenerated
     */
    private String orderCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.ACCOUNT_ID
     *
     * @mbggenerated
     */
    private Integer accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.TYPE_ID
     *
     * @mbggenerated
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.SUBTYPE_ID
     *
     * @mbggenerated
     */
    private Integer subtypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.ORDER_TYPE
     *
     * @mbggenerated
     */
    private String orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.ORDER_RMB
     *
     * @mbggenerated
     */
    private String orderRmb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.PAY_RMB
     *
     * @mbggenerated
     */
    private String payRmb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.ACCEPT_DATE
     *
     * @mbggenerated
     */
    private Timestamp acceptDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.ORDER_STATUS
     *
     * @mbggenerated
     */
    private String orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.STATUS_HIS
     *
     * @mbggenerated
     */
    private String statusHis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.FILE_IDS
     *
     * @mbggenerated
     */
    private String fileIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.REFUND_ID
     *
     * @mbggenerated
     */
    private Integer refundId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.ARBITRATE_ID
     *
     * @mbggenerated
     */
    private Integer arbitrateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.RATE_ID
     *
     * @mbggenerated
     */
    private String rateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.RATE_CONTENT
     *
     * @mbggenerated
     */
    private String rateContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.RATE_DATE
     *
     * @mbggenerated
     */
    private Timestamp rateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.RATE_USER
     *
     * @mbggenerated
     */
    private Integer rateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.OPER_DATE
     *
     * @mbggenerated
     */
    private Timestamp operDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.OPER_DESC
     *
     * @mbggenerated
     */
    private String operDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.IS_PRINT
     *
     * @mbggenerated
     */
    private String isPrint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.BILL_INFO
     *
     * @mbggenerated
     */
    private String billInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.IS_DEL
     *
     * @mbggenerated
     */
    private String isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.CREATE_USER
     *
     * @mbggenerated
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.CREATE_DATE
     *
     * @mbggenerated
     */
    private Timestamp createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.UPDATE_USER
     *
     * @mbggenerated
     */
    private Integer updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.UPDATE_DATE
     *
     * @mbggenerated
     */
    private Timestamp updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.ID
     *
     * @return the value of t_order_info.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.ID
     *
     * @param id the value for t_order_info.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.ORDER_CODE
     *
     * @return the value of t_order_info.ORDER_CODE
     *
     * @mbggenerated
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.ORDER_CODE
     *
     * @param orderCode the value for t_order_info.ORDER_CODE
     *
     * @mbggenerated
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode == null ? null : orderCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.ACCOUNT_ID
     *
     * @return the value of t_order_info.ACCOUNT_ID
     *
     * @mbggenerated
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.ACCOUNT_ID
     *
     * @param accountId the value for t_order_info.ACCOUNT_ID
     *
     * @mbggenerated
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.TYPE_ID
     *
     * @return the value of t_order_info.TYPE_ID
     *
     * @mbggenerated
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.TYPE_ID
     *
     * @param typeId the value for t_order_info.TYPE_ID
     *
     * @mbggenerated
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.SUBTYPE_ID
     *
     * @return the value of t_order_info.SUBTYPE_ID
     *
     * @mbggenerated
     */
    public Integer getSubtypeId() {
        return subtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.SUBTYPE_ID
     *
     * @param subtypeId the value for t_order_info.SUBTYPE_ID
     *
     * @mbggenerated
     */
    public void setSubtypeId(Integer subtypeId) {
        this.subtypeId = subtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.ORDER_TYPE
     *
     * @return the value of t_order_info.ORDER_TYPE
     *
     * @mbggenerated
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.ORDER_TYPE
     *
     * @param orderType the value for t_order_info.ORDER_TYPE
     *
     * @mbggenerated
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType == null ? null : orderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.ORDER_RMB
     *
     * @return the value of t_order_info.ORDER_RMB
     *
     * @mbggenerated
     */
    public String getOrderRmb() {
        return orderRmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.ORDER_RMB
     *
     * @param orderRmb the value for t_order_info.ORDER_RMB
     *
     * @mbggenerated
     */
    public void setOrderRmb(String orderRmb) {
        this.orderRmb = orderRmb == null ? null : orderRmb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.PAY_RMB
     *
     * @return the value of t_order_info.PAY_RMB
     *
     * @mbggenerated
     */
    public String getPayRmb() {
        return payRmb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.PAY_RMB
     *
     * @param payRmb the value for t_order_info.PAY_RMB
     *
     * @mbggenerated
     */
    public void setPayRmb(String payRmb) {
        this.payRmb = payRmb == null ? null : payRmb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.ACCEPT_DATE
     *
     * @return the value of t_order_info.ACCEPT_DATE
     *
     * @mbggenerated
     */
    public Timestamp getAcceptDate() {
        return acceptDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.ACCEPT_DATE
     *
     * @param acceptDate the value for t_order_info.ACCEPT_DATE
     *
     * @mbggenerated
     */
    public void setAcceptDate(Timestamp acceptDate) {
        this.acceptDate = acceptDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.ORDER_STATUS
     *
     * @return the value of t_order_info.ORDER_STATUS
     *
     * @mbggenerated
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.ORDER_STATUS
     *
     * @param orderStatus the value for t_order_info.ORDER_STATUS
     *
     * @mbggenerated
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.STATUS_HIS
     *
     * @return the value of t_order_info.STATUS_HIS
     *
     * @mbggenerated
     */
    public String getStatusHis() {
        return statusHis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.STATUS_HIS
     *
     * @param statusHis the value for t_order_info.STATUS_HIS
     *
     * @mbggenerated
     */
    public void setStatusHis(String statusHis) {
        this.statusHis = statusHis == null ? null : statusHis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.FILE_IDS
     *
     * @return the value of t_order_info.FILE_IDS
     *
     * @mbggenerated
     */
    public String getFileIds() {
        return fileIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.FILE_IDS
     *
     * @param fileIds the value for t_order_info.FILE_IDS
     *
     * @mbggenerated
     */
    public void setFileIds(String fileIds) {
        this.fileIds = fileIds == null ? null : fileIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.REFUND_ID
     *
     * @return the value of t_order_info.REFUND_ID
     *
     * @mbggenerated
     */
    public Integer getRefundId() {
        return refundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.REFUND_ID
     *
     * @param refundId the value for t_order_info.REFUND_ID
     *
     * @mbggenerated
     */
    public void setRefundId(Integer refundId) {
        this.refundId = refundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.ARBITRATE_ID
     *
     * @return the value of t_order_info.ARBITRATE_ID
     *
     * @mbggenerated
     */
    public Integer getArbitrateId() {
        return arbitrateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.ARBITRATE_ID
     *
     * @param arbitrateId the value for t_order_info.ARBITRATE_ID
     *
     * @mbggenerated
     */
    public void setArbitrateId(Integer arbitrateId) {
        this.arbitrateId = arbitrateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.RATE_ID
     *
     * @return the value of t_order_info.RATE_ID
     *
     * @mbggenerated
     */
    public String getRateId() {
        return rateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.RATE_ID
     *
     * @param rateId the value for t_order_info.RATE_ID
     *
     * @mbggenerated
     */
    public void setRateId(String rateId) {
        this.rateId = rateId == null ? null : rateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.RATE_CONTENT
     *
     * @return the value of t_order_info.RATE_CONTENT
     *
     * @mbggenerated
     */
    public String getRateContent() {
        return rateContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.RATE_CONTENT
     *
     * @param rateContent the value for t_order_info.RATE_CONTENT
     *
     * @mbggenerated
     */
    public void setRateContent(String rateContent) {
        this.rateContent = rateContent == null ? null : rateContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.RATE_DATE
     *
     * @return the value of t_order_info.RATE_DATE
     *
     * @mbggenerated
     */
    public Timestamp getRateDate() {
        return rateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.RATE_DATE
     *
     * @param rateDate the value for t_order_info.RATE_DATE
     *
     * @mbggenerated
     */
    public void setRateDate(Timestamp rateDate) {
        this.rateDate = rateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.RATE_USER
     *
     * @return the value of t_order_info.RATE_USER
     *
     * @mbggenerated
     */
    public Integer getRateUser() {
        return rateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.RATE_USER
     *
     * @param rateUser the value for t_order_info.RATE_USER
     *
     * @mbggenerated
     */
    public void setRateUser(Integer rateUser) {
        this.rateUser = rateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.OPER_DATE
     *
     * @return the value of t_order_info.OPER_DATE
     *
     * @mbggenerated
     */
    public Timestamp getOperDate() {
        return operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.OPER_DATE
     *
     * @param operDate the value for t_order_info.OPER_DATE
     *
     * @mbggenerated
     */
    public void setOperDate(Timestamp operDate) {
        this.operDate = operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.OPER_DESC
     *
     * @return the value of t_order_info.OPER_DESC
     *
     * @mbggenerated
     */
    public String getOperDesc() {
        return operDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.OPER_DESC
     *
     * @param operDesc the value for t_order_info.OPER_DESC
     *
     * @mbggenerated
     */
    public void setOperDesc(String operDesc) {
        this.operDesc = operDesc == null ? null : operDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.IS_PRINT
     *
     * @return the value of t_order_info.IS_PRINT
     *
     * @mbggenerated
     */
    public String getIsPrint() {
        return isPrint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.IS_PRINT
     *
     * @param isPrint the value for t_order_info.IS_PRINT
     *
     * @mbggenerated
     */
    public void setIsPrint(String isPrint) {
        this.isPrint = isPrint == null ? null : isPrint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.BILL_INFO
     *
     * @return the value of t_order_info.BILL_INFO
     *
     * @mbggenerated
     */
    public String getBillInfo() {
        return billInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.BILL_INFO
     *
     * @param billInfo the value for t_order_info.BILL_INFO
     *
     * @mbggenerated
     */
    public void setBillInfo(String billInfo) {
        this.billInfo = billInfo == null ? null : billInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.IS_DEL
     *
     * @return the value of t_order_info.IS_DEL
     *
     * @mbggenerated
     */
    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.IS_DEL
     *
     * @param isDel the value for t_order_info.IS_DEL
     *
     * @mbggenerated
     */
    public void setIsDel(String isDel) {
        this.isDel = isDel == null ? null : isDel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.CREATE_USER
     *
     * @return the value of t_order_info.CREATE_USER
     *
     * @mbggenerated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.CREATE_USER
     *
     * @param createUser the value for t_order_info.CREATE_USER
     *
     * @mbggenerated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.CREATE_DATE
     *
     * @return the value of t_order_info.CREATE_DATE
     *
     * @mbggenerated
     */
    public Timestamp getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.CREATE_DATE
     *
     * @param createDate the value for t_order_info.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Timestamp createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.UPDATE_USER
     *
     * @return the value of t_order_info.UPDATE_USER
     *
     * @mbggenerated
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.UPDATE_USER
     *
     * @param updateUser the value for t_order_info.UPDATE_USER
     *
     * @mbggenerated
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.UPDATE_DATE
     *
     * @return the value of t_order_info.UPDATE_DATE
     *
     * @mbggenerated
     */
    public Timestamp getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.UPDATE_DATE
     *
     * @param updateDate the value for t_order_info.UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setUpdateDate(Timestamp updateDate) {
        this.updateDate = updateDate;
    }
}