package com.wisdom.dao.mapper;

import com.wisdom.dao.entity.Nurse;
import com.wisdom.dao.entity.NurseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NurseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_nurse
     *
     * @mbggenerated
     */
    int countByExample(NurseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_nurse
     *
     * @mbggenerated
     */
    int deleteByExample(NurseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_nurse
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_nurse
     *
     * @mbggenerated
     */
    int insert(Nurse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_nurse
     *
     * @mbggenerated
     */
    int insertSelective(Nurse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_nurse
     *
     * @mbggenerated
     */
    List<Nurse> selectByExample(NurseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_nurse
     *
     * @mbggenerated
     */
    Nurse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_nurse
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Nurse record, @Param("example") NurseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_nurse
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Nurse record, @Param("example") NurseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_nurse
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Nurse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_nurse
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Nurse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_nurse
     *
     * @mbggenerated
     */
    void insertBatch(List<Nurse> recordLst);
}