package com.wisdom.dao.mapper;

import com.wisdom.dao.entity.RecoverConfig;
import com.wisdom.dao.entity.RecoverConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RecoverConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recover_config
     *
     * @mbggenerated
     */
    int countByExample(RecoverConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recover_config
     *
     * @mbggenerated
     */
    int deleteByExample(RecoverConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recover_config
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recover_config
     *
     * @mbggenerated
     */
    int insert(RecoverConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recover_config
     *
     * @mbggenerated
     */
    int insertSelective(RecoverConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recover_config
     *
     * @mbggenerated
     */
    List<RecoverConfig> selectByExample(RecoverConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recover_config
     *
     * @mbggenerated
     */
    RecoverConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recover_config
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RecoverConfig record, @Param("example") RecoverConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recover_config
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RecoverConfig record, @Param("example") RecoverConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recover_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RecoverConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recover_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RecoverConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recover_config
     *
     * @mbggenerated
     */
    void insertBatch(List<RecoverConfig> recordLst);
}