package com.wisdom.dao.mapper;

import com.wisdom.dao.entity.RecoverPhoto;
import com.wisdom.dao.entity.RecoverPhotoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RecoverPhotoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recover_photo
     *
     * @mbggenerated
     */
    int countByExample(RecoverPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recover_photo
     *
     * @mbggenerated
     */
    int deleteByExample(RecoverPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recover_photo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recover_photo
     *
     * @mbggenerated
     */
    int insert(RecoverPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recover_photo
     *
     * @mbggenerated
     */
    int insertSelective(RecoverPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recover_photo
     *
     * @mbggenerated
     */
    List<RecoverPhoto> selectByExample(RecoverPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recover_photo
     *
     * @mbggenerated
     */
    RecoverPhoto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recover_photo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RecoverPhoto record, @Param("example") RecoverPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recover_photo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RecoverPhoto record, @Param("example") RecoverPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recover_photo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RecoverPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recover_photo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RecoverPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recover_photo
     *
     * @mbggenerated
     */
    void insertBatch(List<RecoverPhoto> recordLst);
}