package com.wisdom.dao.mapper;

import com.wisdom.dao.entity.SysParam;
import com.wisdom.dao.entity.SysParamExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_param
     *
     * @mbggenerated
     */
    int countByExample(SysParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_param
     *
     * @mbggenerated
     */
    int deleteByExample(SysParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_param
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_param
     *
     * @mbggenerated
     */
    int insert(SysParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_param
     *
     * @mbggenerated
     */
    int insertSelective(SysParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_param
     *
     * @mbggenerated
     */
    List<SysParam> selectByExample(SysParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_param
     *
     * @mbggenerated
     */
    SysParam selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_param
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysParam record, @Param("example") SysParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_param
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysParam record, @Param("example") SysParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_param
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_param
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_param
     *
     * @mbggenerated
     */
    void insertBatch(List<SysParam> recordLst);
}