package com.wisdom.dao.entity;

import java.io.Serializable;
import java.sql.Timestamp;

public class FileUploadRecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_upload_record.BUSI_SN
     *
     * @mbggenerated
     */
    private Long busiSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_upload_record.FILE_ID
     *
     * @mbggenerated
     */
    private String fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_upload_record.FILE_SERVER
     *
     * @mbggenerated
     */
    private String fileServer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_upload_record.FILE_NAME
     *
     * @mbggenerated
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_upload_record.FILE_PATH
     *
     * @mbggenerated
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_upload_record.OPTR_TYPE
     *
     * @mbggenerated
     */
    private Integer optrType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_upload_record.OPTR_DATE
     *
     * @mbggenerated
     */
    private Timestamp optrDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_upload_record.USER_ID
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file_upload_record
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_upload_record.BUSI_SN
     *
     * @return the value of file_upload_record.BUSI_SN
     *
     * @mbggenerated
     */
    public Long getBusiSn() {
        return busiSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_upload_record.BUSI_SN
     *
     * @param busiSn the value for file_upload_record.BUSI_SN
     *
     * @mbggenerated
     */
    public void setBusiSn(Long busiSn) {
        this.busiSn = busiSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_upload_record.FILE_ID
     *
     * @return the value of file_upload_record.FILE_ID
     *
     * @mbggenerated
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_upload_record.FILE_ID
     *
     * @param fileId the value for file_upload_record.FILE_ID
     *
     * @mbggenerated
     */
    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_upload_record.FILE_SERVER
     *
     * @return the value of file_upload_record.FILE_SERVER
     *
     * @mbggenerated
     */
    public String getFileServer() {
        return fileServer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_upload_record.FILE_SERVER
     *
     * @param fileServer the value for file_upload_record.FILE_SERVER
     *
     * @mbggenerated
     */
    public void setFileServer(String fileServer) {
        this.fileServer = fileServer == null ? null : fileServer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_upload_record.FILE_NAME
     *
     * @return the value of file_upload_record.FILE_NAME
     *
     * @mbggenerated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_upload_record.FILE_NAME
     *
     * @param fileName the value for file_upload_record.FILE_NAME
     *
     * @mbggenerated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_upload_record.FILE_PATH
     *
     * @return the value of file_upload_record.FILE_PATH
     *
     * @mbggenerated
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_upload_record.FILE_PATH
     *
     * @param filePath the value for file_upload_record.FILE_PATH
     *
     * @mbggenerated
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_upload_record.OPTR_TYPE
     *
     * @return the value of file_upload_record.OPTR_TYPE
     *
     * @mbggenerated
     */
    public Integer getOptrType() {
        return optrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_upload_record.OPTR_TYPE
     *
     * @param optrType the value for file_upload_record.OPTR_TYPE
     *
     * @mbggenerated
     */
    public void setOptrType(Integer optrType) {
        this.optrType = optrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_upload_record.OPTR_DATE
     *
     * @return the value of file_upload_record.OPTR_DATE
     *
     * @mbggenerated
     */
    public Timestamp getOptrDate() {
        return optrDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_upload_record.OPTR_DATE
     *
     * @param optrDate the value for file_upload_record.OPTR_DATE
     *
     * @mbggenerated
     */
    public void setOptrDate(Timestamp optrDate) {
        this.optrDate = optrDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_upload_record.USER_ID
     *
     * @return the value of file_upload_record.USER_ID
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_upload_record.USER_ID
     *
     * @param userId the value for file_upload_record.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}