package com.wisdom.dao.mapper;

import com.wisdom.dao.entity.Device;
import com.wisdom.dao.entity.DeviceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device
     *
     * @mbggenerated
     */
    int countByExample(DeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device
     *
     * @mbggenerated
     */
    int deleteByExample(DeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device
     *
     * @mbggenerated
     */
    int insert(Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device
     *
     * @mbggenerated
     */
    int insertSelective(Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device
     *
     * @mbggenerated
     */
    List<Device> selectByExample(DeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device
     *
     * @mbggenerated
     */
    Device selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Device record, @Param("example") DeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Device record, @Param("example") DeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device
     *
     * @mbggenerated
     */
    void insertBatch(List<Device> recordLst);
}