package com.wisdom.dao.mapper;

import com.wisdom.dao.entity.Hospital;
import com.wisdom.dao.entity.HospitalExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HospitalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hospital
     *
     * @mbggenerated
     */
    int countByExample(HospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hospital
     *
     * @mbggenerated
     */
    int deleteByExample(HospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hospital
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hospital
     *
     * @mbggenerated
     */
    int insert(Hospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hospital
     *
     * @mbggenerated
     */
    int insertSelective(Hospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hospital
     *
     * @mbggenerated
     */
    List<Hospital> selectByExample(HospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hospital
     *
     * @mbggenerated
     */
    Hospital selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hospital
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Hospital record, @Param("example") HospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hospital
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Hospital record, @Param("example") HospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hospital
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Hospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hospital
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Hospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hospital
     *
     * @mbggenerated
     */
    void insertBatch(List<Hospital> recordLst);
}