package com.wisdom.dao.mapper;

import com.wisdom.dao.entity.Recover;
import com.wisdom.dao.entity.RecoverExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RecoverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recover
     *
     * @mbggenerated
     */
    int countByExample(RecoverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recover
     *
     * @mbggenerated
     */
    int deleteByExample(RecoverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recover
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recover
     *
     * @mbggenerated
     */
    int insert(Recover record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recover
     *
     * @mbggenerated
     */
    int insertSelective(Recover record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recover
     *
     * @mbggenerated
     */
    List<Recover> selectByExample(RecoverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recover
     *
     * @mbggenerated
     */
    Recover selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recover
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Recover record, @Param("example") RecoverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recover
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Recover record, @Param("example") RecoverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recover
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Recover record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recover
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Recover record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recover
     *
     * @mbggenerated
     */
    void insertBatch(List<Recover> recordLst);
}