package com.wisdom.dao.entity;

import java.io.Serializable;
import java.sql.Timestamp;

public class Nurse implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nurse.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nurse.ACCOUNT_ID
     *
     * @mbggenerated
     */
    private Integer accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nurse.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nurse.SEX
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nurse.AGE
     *
     * @mbggenerated
     */
    private String age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nurse.SIMPLE_PINYIN
     *
     * @mbggenerated
     */
    private String simplePinyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nurse.ID_CODE
     *
     * @mbggenerated
     */
    private String idCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nurse.ID_PATH
     *
     * @mbggenerated
     */
    private String idPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nurse.RELATION
     *
     * @mbggenerated
     */
    private String relation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nurse.WORK_YEARS
     *
     * @mbggenerated
     */
    private String workYears;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nurse.WORK_HOSPITAL
     *
     * @mbggenerated
     */
    private Integer workHospital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nurse.WORK_DEPARTMENT
     *
     * @mbggenerated
     */
    private Integer workDepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nurse.GOOD_RANGE
     *
     * @mbggenerated
     */
    private String goodRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nurse.SERVICE_RANGE
     *
     * @mbggenerated
     */
    private String serviceRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nurse.LICENSE
     *
     * @mbggenerated
     */
    private String license;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nurse.IS_DEL
     *
     * @mbggenerated
     */
    private String isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nurse.CREATE_DATE
     *
     * @mbggenerated
     */
    private Timestamp createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_nurse
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nurse.ID
     *
     * @return the value of t_nurse.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nurse.ID
     *
     * @param id the value for t_nurse.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nurse.ACCOUNT_ID
     *
     * @return the value of t_nurse.ACCOUNT_ID
     *
     * @mbggenerated
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nurse.ACCOUNT_ID
     *
     * @param accountId the value for t_nurse.ACCOUNT_ID
     *
     * @mbggenerated
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nurse.NAME
     *
     * @return the value of t_nurse.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nurse.NAME
     *
     * @param name the value for t_nurse.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nurse.SEX
     *
     * @return the value of t_nurse.SEX
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nurse.SEX
     *
     * @param sex the value for t_nurse.SEX
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nurse.AGE
     *
     * @return the value of t_nurse.AGE
     *
     * @mbggenerated
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nurse.AGE
     *
     * @param age the value for t_nurse.AGE
     *
     * @mbggenerated
     */
    public void setAge(String age) {
        this.age = age == null ? null : age.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nurse.SIMPLE_PINYIN
     *
     * @return the value of t_nurse.SIMPLE_PINYIN
     *
     * @mbggenerated
     */
    public String getSimplePinyin() {
        return simplePinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nurse.SIMPLE_PINYIN
     *
     * @param simplePinyin the value for t_nurse.SIMPLE_PINYIN
     *
     * @mbggenerated
     */
    public void setSimplePinyin(String simplePinyin) {
        this.simplePinyin = simplePinyin == null ? null : simplePinyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nurse.ID_CODE
     *
     * @return the value of t_nurse.ID_CODE
     *
     * @mbggenerated
     */
    public String getIdCode() {
        return idCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nurse.ID_CODE
     *
     * @param idCode the value for t_nurse.ID_CODE
     *
     * @mbggenerated
     */
    public void setIdCode(String idCode) {
        this.idCode = idCode == null ? null : idCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nurse.ID_PATH
     *
     * @return the value of t_nurse.ID_PATH
     *
     * @mbggenerated
     */
    public String getIdPath() {
        return idPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nurse.ID_PATH
     *
     * @param idPath the value for t_nurse.ID_PATH
     *
     * @mbggenerated
     */
    public void setIdPath(String idPath) {
        this.idPath = idPath == null ? null : idPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nurse.RELATION
     *
     * @return the value of t_nurse.RELATION
     *
     * @mbggenerated
     */
    public String getRelation() {
        return relation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nurse.RELATION
     *
     * @param relation the value for t_nurse.RELATION
     *
     * @mbggenerated
     */
    public void setRelation(String relation) {
        this.relation = relation == null ? null : relation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nurse.WORK_YEARS
     *
     * @return the value of t_nurse.WORK_YEARS
     *
     * @mbggenerated
     */
    public String getWorkYears() {
        return workYears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nurse.WORK_YEARS
     *
     * @param workYears the value for t_nurse.WORK_YEARS
     *
     * @mbggenerated
     */
    public void setWorkYears(String workYears) {
        this.workYears = workYears == null ? null : workYears.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nurse.WORK_HOSPITAL
     *
     * @return the value of t_nurse.WORK_HOSPITAL
     *
     * @mbggenerated
     */
    public Integer getWorkHospital() {
        return workHospital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nurse.WORK_HOSPITAL
     *
     * @param workHospital the value for t_nurse.WORK_HOSPITAL
     *
     * @mbggenerated
     */
    public void setWorkHospital(Integer workHospital) {
        this.workHospital = workHospital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nurse.WORK_DEPARTMENT
     *
     * @return the value of t_nurse.WORK_DEPARTMENT
     *
     * @mbggenerated
     */
    public Integer getWorkDepartment() {
        return workDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nurse.WORK_DEPARTMENT
     *
     * @param workDepartment the value for t_nurse.WORK_DEPARTMENT
     *
     * @mbggenerated
     */
    public void setWorkDepartment(Integer workDepartment) {
        this.workDepartment = workDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nurse.GOOD_RANGE
     *
     * @return the value of t_nurse.GOOD_RANGE
     *
     * @mbggenerated
     */
    public String getGoodRange() {
        return goodRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nurse.GOOD_RANGE
     *
     * @param goodRange the value for t_nurse.GOOD_RANGE
     *
     * @mbggenerated
     */
    public void setGoodRange(String goodRange) {
        this.goodRange = goodRange == null ? null : goodRange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nurse.SERVICE_RANGE
     *
     * @return the value of t_nurse.SERVICE_RANGE
     *
     * @mbggenerated
     */
    public String getServiceRange() {
        return serviceRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nurse.SERVICE_RANGE
     *
     * @param serviceRange the value for t_nurse.SERVICE_RANGE
     *
     * @mbggenerated
     */
    public void setServiceRange(String serviceRange) {
        this.serviceRange = serviceRange == null ? null : serviceRange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nurse.LICENSE
     *
     * @return the value of t_nurse.LICENSE
     *
     * @mbggenerated
     */
    public String getLicense() {
        return license;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nurse.LICENSE
     *
     * @param license the value for t_nurse.LICENSE
     *
     * @mbggenerated
     */
    public void setLicense(String license) {
        this.license = license == null ? null : license.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nurse.IS_DEL
     *
     * @return the value of t_nurse.IS_DEL
     *
     * @mbggenerated
     */
    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nurse.IS_DEL
     *
     * @param isDel the value for t_nurse.IS_DEL
     *
     * @mbggenerated
     */
    public void setIsDel(String isDel) {
        this.isDel = isDel == null ? null : isDel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nurse.CREATE_DATE
     *
     * @return the value of t_nurse.CREATE_DATE
     *
     * @mbggenerated
     */
    public Timestamp getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nurse.CREATE_DATE
     *
     * @param createDate the value for t_nurse.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Timestamp createDate) {
        this.createDate = createDate;
    }
}