package com.wisdom.dao.entity;

import java.io.Serializable;
import java.sql.Timestamp;

public class WeChatLogin implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wechat_login.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wechat_login.ACCOUNT_ID
     *
     * @mbggenerated
     */
    private Integer accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wechat_login.ACCOUNT_TYPE
     *
     * @mbggenerated
     */
    private String accountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wechat_login.WECHAT_ID
     *
     * @mbggenerated
     */
    private String wechatId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wechat_login.NICK_NAME
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wechat_login.HEADIMG_URL
     *
     * @mbggenerated
     */
    private String headimgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wechat_login.SEX
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wechat_login.CITY
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wechat_login.PROVINCE
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wechat_login.COUNTRY
     *
     * @mbggenerated
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wechat_login.LAST_LOGINIP
     *
     * @mbggenerated
     */
    private String lastLoginip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wechat_login.LAST_LOGINTIME
     *
     * @mbggenerated
     */
    private Timestamp lastLogintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wechat_login.LOGIN_TIME
     *
     * @mbggenerated
     */
    private Timestamp loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wechat_login.LOGIN_IP
     *
     * @mbggenerated
     */
    private String loginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_wechat_login
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wechat_login.ID
     *
     * @return the value of t_wechat_login.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wechat_login.ID
     *
     * @param id the value for t_wechat_login.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wechat_login.ACCOUNT_ID
     *
     * @return the value of t_wechat_login.ACCOUNT_ID
     *
     * @mbggenerated
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wechat_login.ACCOUNT_ID
     *
     * @param accountId the value for t_wechat_login.ACCOUNT_ID
     *
     * @mbggenerated
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wechat_login.ACCOUNT_TYPE
     *
     * @return the value of t_wechat_login.ACCOUNT_TYPE
     *
     * @mbggenerated
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wechat_login.ACCOUNT_TYPE
     *
     * @param accountType the value for t_wechat_login.ACCOUNT_TYPE
     *
     * @mbggenerated
     */
    public void setAccountType(String accountType) {
        this.accountType = accountType == null ? null : accountType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wechat_login.WECHAT_ID
     *
     * @return the value of t_wechat_login.WECHAT_ID
     *
     * @mbggenerated
     */
    public String getWechatId() {
        return wechatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wechat_login.WECHAT_ID
     *
     * @param wechatId the value for t_wechat_login.WECHAT_ID
     *
     * @mbggenerated
     */
    public void setWechatId(String wechatId) {
        this.wechatId = wechatId == null ? null : wechatId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wechat_login.NICK_NAME
     *
     * @return the value of t_wechat_login.NICK_NAME
     *
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wechat_login.NICK_NAME
     *
     * @param nickName the value for t_wechat_login.NICK_NAME
     *
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wechat_login.HEADIMG_URL
     *
     * @return the value of t_wechat_login.HEADIMG_URL
     *
     * @mbggenerated
     */
    public String getHeadimgUrl() {
        return headimgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wechat_login.HEADIMG_URL
     *
     * @param headimgUrl the value for t_wechat_login.HEADIMG_URL
     *
     * @mbggenerated
     */
    public void setHeadimgUrl(String headimgUrl) {
        this.headimgUrl = headimgUrl == null ? null : headimgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wechat_login.SEX
     *
     * @return the value of t_wechat_login.SEX
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wechat_login.SEX
     *
     * @param sex the value for t_wechat_login.SEX
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wechat_login.CITY
     *
     * @return the value of t_wechat_login.CITY
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wechat_login.CITY
     *
     * @param city the value for t_wechat_login.CITY
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wechat_login.PROVINCE
     *
     * @return the value of t_wechat_login.PROVINCE
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wechat_login.PROVINCE
     *
     * @param province the value for t_wechat_login.PROVINCE
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wechat_login.COUNTRY
     *
     * @return the value of t_wechat_login.COUNTRY
     *
     * @mbggenerated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wechat_login.COUNTRY
     *
     * @param country the value for t_wechat_login.COUNTRY
     *
     * @mbggenerated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wechat_login.LAST_LOGINIP
     *
     * @return the value of t_wechat_login.LAST_LOGINIP
     *
     * @mbggenerated
     */
    public String getLastLoginip() {
        return lastLoginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wechat_login.LAST_LOGINIP
     *
     * @param lastLoginip the value for t_wechat_login.LAST_LOGINIP
     *
     * @mbggenerated
     */
    public void setLastLoginip(String lastLoginip) {
        this.lastLoginip = lastLoginip == null ? null : lastLoginip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wechat_login.LAST_LOGINTIME
     *
     * @return the value of t_wechat_login.LAST_LOGINTIME
     *
     * @mbggenerated
     */
    public Timestamp getLastLogintime() {
        return lastLogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wechat_login.LAST_LOGINTIME
     *
     * @param lastLogintime the value for t_wechat_login.LAST_LOGINTIME
     *
     * @mbggenerated
     */
    public void setLastLogintime(Timestamp lastLogintime) {
        this.lastLogintime = lastLogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wechat_login.LOGIN_TIME
     *
     * @return the value of t_wechat_login.LOGIN_TIME
     *
     * @mbggenerated
     */
    public Timestamp getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wechat_login.LOGIN_TIME
     *
     * @param loginTime the value for t_wechat_login.LOGIN_TIME
     *
     * @mbggenerated
     */
    public void setLoginTime(Timestamp loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wechat_login.LOGIN_IP
     *
     * @return the value of t_wechat_login.LOGIN_IP
     *
     * @mbggenerated
     */
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wechat_login.LOGIN_IP
     *
     * @param loginIp the value for t_wechat_login.LOGIN_IP
     *
     * @mbggenerated
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp == null ? null : loginIp.trim();
    }
}